// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "N-Circled",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "N-Circled",
            targets: ["AppModule"],
            bundleIdentifier: "-.N-Circled",
            teamIdentifier: "949D776DFQ",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-numerics.git", "1.0.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ComplexModule", package: "swift-numerics")
            ],
            path: "."
        )
    ]
)